//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Emojis = new HashSet<Emoji>();
            this.Emojis1 = new HashSet<Emoji>();
            this.Friends = new HashSet<Friend>();
            this.Friends1 = new HashSet<Friend>();
            this.Messages = new HashSet<Message>();
        }
    
        public int User_Id { get; set; }

        [Required]
        [StringLength(maximumLength: 10, MinimumLength = 1,ErrorMessage ="Name must between 1 and 10")]
        public string UserName { get; set; }

        [Required]
        [Display(Name = "PassWord")]
        [StringLength(maximumLength: 15, MinimumLength = 6,ErrorMessage ="Password must between 6 and 15")]
        public string PassWord { get; set; }

        [NotMapped]
        [Required]
        [Compare("PassWord",ErrorMessage ="Comfirm password not match")]
        public string ConfirmPassword { get; set; }

        [Required]
        [EmailAddress(ErrorMessage = "khong hop le email")]
        public string Email { get; set; }

        [Required]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> DOB { get; set; }

        [Required]
        public Nullable<bool> Gender { get; set; }

        [Required]
        public Nullable<bool> WorkStatus { get; set; }

        [Required]
        public string Address { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emoji> Emojis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emoji> Emojis1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Friend> Friends { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Friend> Friends1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Message> Messages { get; set; }
    }
    public enum Gender
    {
        Male,
        Female
    }

    public enum WorkStatus
    {
        Student,
        Employees
    }
}
